import turtle
import random
import numpy as np


# =========================
# 1. Midpoint Displacement
# =========================

def midpoint_displacement(x1, y1, x2, y2, roughness, depth):
    """
    Return a list of points generated by midpoint displacement.
    """
    if depth < 0:
        raise ValueError("depth must be non-negative")
    if roughness < 0:
        raise ValueError("roughness must be non-negative")

    if depth == 0:
        return [(x1, y1), (x2, y2)]

    xm = (x1 + x2) / 2
    ym = (y1 + y2) / 2 + roughness * random.uniform(-1, 1)

    # smaller roughness at deeper levels -> more natural line
    left_points = midpoint_displacement(x1, y1, xm, ym, roughness * 0.7, depth - 1)
    right_points = midpoint_displacement(xm, ym, x2, y2, roughness * 0.7, depth - 1)

    return left_points[:-1] + right_points


def draw_polyline(t, points):
    if not points:
        return

    t.penup()
    t.goto(points[0])
    t.pendown()

    for p in points[1:]:
        t.goto(p)


def count_midpoints(depth):
    """
    Number of midpoints calculated at recursion depth d.
    """
    if depth < 0:
        raise ValueError("depth must be non-negative")
    return 2 ** depth - 1


# =========================
# 2. Diamond-Square Terrain
# =========================

def diamond_square(terrain, x1, y1, x2, y2, roughness, depth):
    """
    Recursive diamond-square refinement.
    """
    if depth == 0:
        return

    if x2 - x1 < 2 or y2 - y1 < 2:
        return

    xm = (x1 + x2) // 2
    ym = (y1 + y2) // 2

    a = terrain[x1, y1]
    b = terrain[x1, y2]
    c = terrain[x2, y1]
    d = terrain[x2, y2]

    center = (a + b + c + d) / 4
    terrain[xm, ym] = center + roughness * random.uniform(-1, 1)

    if terrain[x1, ym] == 0:
        terrain[x1, ym] = (a + b) / 2 + roughness * random.uniform(-1, 1)
    if terrain[x2, ym] == 0:
        terrain[x2, ym] = (c + d) / 2 + roughness * random.uniform(-1, 1)
    if terrain[xm, y1] == 0:
        terrain[xm, y1] = (a + c) / 2 + roughness * random.uniform(-1, 1)
    if terrain[xm, y2] == 0:
        terrain[xm, y2] = (b + d) / 2 + roughness * random.uniform(-1, 1)

    new_roughness = roughness / 2

    diamond_square(terrain, x1, y1, xm, ym, new_roughness, depth - 1)
    diamond_square(terrain, xm, y1, x2, ym, new_roughness, depth - 1)
    diamond_square(terrain, x1, ym, xm, y2, new_roughness, depth - 1)
    diamond_square(terrain, xm, ym, x2, y2, new_roughness, depth - 1)


def generate_terrain(width, height, roughness, depth):
    """
    Generate a 2D terrain grid.

    Edge cases handled:
    - depth < 0 -> reject
    - width <= 0 or height <= 0 -> reject
    - roughness < 0 -> reject
    - depth = 0 -> return grid with only 4 initialized corners
    """
    if depth < 0:
        raise ValueError("depth must be non-negative")
    if width <= 0 or height <= 0:
        raise ValueError("width and height must be positive")
    if roughness < 0:
        raise ValueError("roughness must be non-negative")

    terrain = np.zeros((width, height), dtype=float)

    # 4 corners at height 0
    terrain[0, 0] = 0
    terrain[0, height - 1] = 0
    terrain[width - 1, 0] = 0
    terrain[width - 1, height - 1] = 0

    if depth == 0:
        return terrain

    diamond_square(terrain, 0, 0, width - 1, height - 1, roughness, depth)
    return terrain


# =========================
# 3. Artifact Detection
# =========================

def detect_artifacts(terrain_grid, threshold):
    """
    Return suspicious coordinates where height changes too abruptly.
    """
    if threshold < 0:
        raise ValueError("threshold must be non-negative")

    artifacts = []
    rows, cols = terrain_grid.shape

    for i in range(rows - 1):
        for j in range(cols - 1):
            if (abs(terrain_grid[i, j] - terrain_grid[i + 1, j]) > threshold or
                abs(terrain_grid[i, j] - terrain_grid[i, j + 1]) > threshold):
                artifacts.append((i, j))

    return artifacts


# =========================
# 4. Turtle Visualization
# =========================

def height_to_color(h, min_h, max_h):
    """
    Convert height to terrain-like color.
    """
    if max_h == min_h:
        return "gray"

    ratio = (h - min_h) / (max_h - min_h)

    if ratio < 0.2:
        return "#1f4e79"   # dark blue
    elif ratio < 0.4:
        return "#4f81bd"   # blue
    elif ratio < 0.6:
        return "#6aa84f"   # green
    elif ratio < 0.8:
        return "#8b5a2b"   # brown
    else:
        return "#f3f3f3"   # snow / light top


def draw_filled_square(t, x, y, size, color):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.fillcolor(color)
    t.pencolor(color)
    t.begin_fill()
    for _ in range(4):
        t.forward(size)
        t.left(90)
    t.end_fill()


def draw_terrain(t, terrain, start_x, start_y, cell_size):
    rows, cols = terrain.shape
    min_h = np.min(terrain)
    max_h = np.max(terrain)

    for i in range(rows):
        for j in range(cols):
            color = height_to_color(terrain[i, j], min_h, max_h)
            x = start_x + j * cell_size
            y = start_y + i * cell_size
            draw_filled_square(t, x, y, cell_size, color)


def draw_artifacts(t, artifacts, start_x, start_y, cell_size):
    t.penup()
    t.color("red")

    for (i, j) in artifacts:
        x = start_x + j * cell_size + cell_size / 2
        y = start_y + i * cell_size + cell_size / 2
        t.goto(x, y)
        t.dot(max(3, cell_size * 0.45))


# =========================
# 5. Edge Case Tests
# =========================

def run_edge_case_tests():
    print("\n=== EX3 Edge Case Tests ===")

    # ---- midpoint_displacement ----
    print("\n1. midpoint_displacement")
    p0 = midpoint_displacement(0, 0, 100, 0, 1, 0)
    print("Edge Case: depth = 0")
    print("Actual result:", p0)

    p1 = midpoint_displacement(0, 0, 100, 0, 0, 4)
    print("Edge Case: roughness = 0")
    print("Actual result: generated", len(p1), "points on a smooth line")

    try:
        midpoint_displacement(0, 0, 100, 0, 1, -1)
    except Exception as e:
        print("Edge Case: negative depth")
        print("Actual result:", e)

    # ---- generate_terrain ----
    print("\n2. generate_terrain")
    terrain0 = generate_terrain(9, 9, 1, 0)
    print("Edge Case: depth = 0")
    print("Actual result: terrain shape =", terrain0.shape)

    terrain1 = generate_terrain(9, 9, 0, 3)
    print("Edge Case: roughness = 0")
    print("Actual result: smoother terrain generated")

    try:
        generate_terrain(0, 9, 1, 2)
    except Exception as e:
        print("Edge Case: invalid grid size")
        print("Actual result:", e)

    # ---- detect_artifacts ----
    print("\n3. detect_artifacts")
    simple = np.array([[0, 1], [2, 3]], dtype=float)

    a0 = detect_artifacts(simple, 0)
    print("Edge Case: threshold = 0")
    print("Actual result: suspicious coordinates =", a0)

    a1 = detect_artifacts(simple, 1000)
    print("Edge Case: very large threshold")
    print("Actual result: suspicious coordinates =", a1)

    try:
        detect_artifacts(simple, -1)
    except Exception as e:
        print("Edge Case: negative threshold")
        print("Actual result:", e)


# =========================
# 6. Main / Demo
# =========================

def main():
    print("=== EX3 Typical Examples ===")

    # Typical example from the question:
    # 1024-pixel line, depth = 10
    n_midpoints = count_midpoints(10)
    print("For a 1024-pixel line with depth 10 -> number of midpoints =", n_midpoints)

    # roughness discussion
    print("If roughness = 0 -> result is smooth and regular")
    print("If roughness = 2 -> result is more irregular and rough")

    # edge-case tests
    run_edge_case_tests()

    # ---------- Turtle setup ----------
    screen = turtle.Screen()
    screen.setup(width=1400, height=850)
    screen.bgcolor("white")
    screen.title("Exercise 3 - Recursive Patterns")
    screen.tracer(0)

    t = turtle.Turtle()
    t.hideturtle()
    t.speed(0)
    t.pensize(2)

    # ---------- Typical example 1: midpoint displacement ----------
    # 1024-pixel line, depth = 10
    t.color("black")
    points = midpoint_displacement(-620, 250, 404, 250, roughness=20, depth=10)
    draw_polyline(t, points)

    # ---------- Typical example 2: terrain ----------
    # start with 4 corners at height 0
    terrain = generate_terrain(33, 33, roughness=12, depth=5)
    draw_terrain(t, terrain, start_x=120, start_y=-260, cell_size=10)

    # ---------- Typical example 3: artifacts ----------
    artifacts = detect_artifacts(terrain, threshold=15)
    print("Detected suspicious coordinates in terrain:", len(artifacts))
    draw_artifacts(t, artifacts, start_x=120, start_y=-260, cell_size=10)

    screen.update()
    turtle.done()


if __name__ == "__main__":
    main()